name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Lint with ruff
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     ruff --format=github --select=E9,F63,F7,F82 --target-version=py39 .
    #     # default set of ruff rules with GitHub Annotations
    #     ruff --format=github --target-version=py39 .

    - name: Test with pytest
      run: |
        python -m pytest